// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using Assets.Code.Interfaces;

namespace Assets.Code.States

{
		public class BeginState : IStateBase
		{
				private StateManager manager;
				private float futureTime = 0;
				private int countDown = 0;
				private float screenDuration = 8;
				

				public BeginState (StateManager managerRef)  //Constructor
				{
					manager = managerRef;
					futureTime = screenDuration + Time.realtimeSinceStartup;
					Debug.Log ("Constructing BeginState");
					if (Application.loadedLevelName != "Scene 0") {
						Application.LoadLevel ("Scene 0");
					}
					
				}

				public void StateUpdate()
				{
					if (Input.GetKeyUp (KeyCode.Space))
					{
						manager.Restart ();
						
				}

				public void ShowIt()
				{
					GUI.DrawTexture (new Rect(0,0,Screen.width,Screen.height), manager.gameDataRef.beginStateSplash, ScaleMode.StretchToFill);
					
					
					if (GUI.Button (new Rect(10,10,250,60), "Press Here or Any Key to Continue") || Input.anyKeyDown) 
					{
						manager.SwitchState (new SetupState (manager));	
					}
					
					GUI.Box (new Rect (Screen.width - 60,10,50,25), countDown.ToString ());
				}
				
				void Switch()
				{
					
				}
				
				public void StateFixedUpdate()
				{

				}
		}
}

