// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using UnityEngine;
using Assets.Code.Interfaces;

namespace Assets.Code.States

{
		public class LostState : IStateBase
		{
				private StateManager manager;
				

				public LostState (StateManager managerRef)  //Constructor
				{
					manager = managerRef;
					Debug.Log ("Constructing LostState");
				}

				public void StateUpdate()
				{
					if (Input.GetKeyUp (KeyCode.Space)) {
						Application.LoadLevel ("BeginningScene");
						manager.SwitchState (new BeginState (manager));
					}
				}

				public void ShowIt()
				{

				}

				public void StateFixedUpdate()
				{

				}
		}
}

